version: 2

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    id: "aws-smtp-relay"
    binary: aws-smtp-relay
    main: ./
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.GitCommit={{.Commit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE.txt
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

dockers_v2:
  # ============================================
  # Distroless images (production - default)
  # ============================================
  - id: distroless
    images:
      - "ghcr.io/kian99/aws-smtp-relay"
    tags:
      - "{{ .Version }}"
      - "latest"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "SMTP server to relay emails via Amazon SES or Pinpoint using IAM roles"
      "org.opencontainers.image.url": "https://github.com/kian99/{{ .ProjectName }}"
      "org.opencontainers.image.source": "https://github.com/kian99/{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ time \"2006-01-02T15:04:05Z07:00\" }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "MIT"

  # ============================================
  # Alpine images (debug - with shell)
  # ============================================
  - id: alpine
    images:
      - "ghcr.io/kian99/aws-smtp-relay"
    tags:
      - "{{ .Version }}-alpine"
      - "latest-alpine"
      - "v{{ .Major }}-alpine"
      - "v{{ .Major }}.{{ .Minor }}-alpine"
    dockerfile: Dockerfile.alpine
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "SMTP server to relay emails via Amazon SES or Pinpoint using IAM roles (Alpine variant with shell)"
      "org.opencontainers.image.url": "https://github.com/kian99/{{ .ProjectName }}"
      "org.opencontainers.image.source": "https://github.com/kian99/{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ time \"2006-01-02T15:04:05Z07:00\" }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "MIT"

release:
  github:
    owner: kian99
    name: aws-smtp-relay
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{ .Version }}

    **Full Changelog**: https://github.com/kian99/aws-smtp-relay/compare/{{ .PreviousTag }}...{{ .Tag }}
  footer: |
    ## Docker Images

    Both Docker Hub and GitHub Container Registry are supported:

    **Production (Distroless - recommended):**
    ```bash
    docker pull ghcr.io/kian99/aws-smtp-relay:{{ .Version }}
    ```

    **Debug (Alpine - with shell):**
    ```bash
    docker pull ghcr.io/kian99/aws-smtp-relay:{{ .Version }}-alpine
    ```

    **Binaries:**
    Download pre-compiled binaries for your platform from the assets below.
