before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    id: "aws-smtp-relay"
    ldflags:
      - "-s -w -X main.Version='{{.Version}}' -X main.GitCommit={{.Commit}}"
#      - freebsd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - amd64
      - arm64
#      - 386
    goarm:
      - 6
      - 7
    main: ./
    binary: aws-smtp-relay
    tags:
      - release

archives:
  - id: archive_id
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- .Arm }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# .goreleaser.yaml
dockers:
- image_templates: ["ghcr.io/kamorionlabs/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/KamorionLabs/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/KamorionLabs/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

- image_templates: ["ghcr.io/kamorionlabs/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/KamorionLabs/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/KamorionLabs/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

- image_templates: ["ghcr.io/kamorionlabs/{{ .ProjectName }}:{{ .Version }}-armv7"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --platform=linux/arm/v7
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/KamorionLabs/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/KamorionLabs/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
- name_template: ghcr.io/kamorionlabs/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/kamorionlabs/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/kamorionlabs/{{ .ProjectName }}:{{ .Version }}-armv7
  - ghcr.io/kamorionlabs/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/kamorionlabs/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/kamorionlabs/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/kamorionlabs/{{ .ProjectName }}:{{ .Version }}-armv7
  - ghcr.io/kamorionlabs/{{ .ProjectName }}:{{ .Version }}-arm64v8
